### ISSUE TITLE
## EKS-KIC

### ISSUE THREAD

**Issue by yossi-r** [f5devcentral/f5-digital-customer-engagement-center#11]
The solution will be delivered 3/4

- Terraform Modules needed for this lab
  - [x] AWS MIN
  - [x] UDF Jumphost
  - [x] EKS
  - [x] ECR
      https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html
     ```bash
      aws ecr get-login-password --region region | docker login --username AWS --password-stdin 
      aws_account_id.dkr.ecr.region.amazonaws.com
     ```
     worker nodes need ecr access
    ```
    Policy with name AmazonEC2ContainerRegistryReadOnly, AmazonEC2ContainerRegistryPowerUser should be associated
    ```
  - [x] workstation
  - [x] Configuration (demo script)
  - [x] Lab Guide (drafted and cleaned, needs testing docs/delivery/application_delivery_controller/nginx/kic/lab*)
  - [ ] Presentation (requested from PM Karthik)
  - [x] Application

Working Steps:
https://github.com/f5devcentral/terraform-gcp-f5-sca/blob/main/demo/cis-kic/setup.sh

1. [x] Add ECR
2. [x] Add IAM to EKS
3. [x] awscli from Workstation to ECR
4. [ ] awscli key/cert nginx+ to Secrets Manager - This is now out of scope
4. [x] Workstation Build Ingress image push to ECR

**Comment by jmcalalang** [comment]
@vinnie357 UDF blueprint has the same project name. this can be used for labs

**Comment by jmcalalang** [comment]
issue #42 is tied to this, since we needed a udf solution for the labs
