### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by vinnie357** [f5devcentral/f5-digital-customer-engagement-center#13]
- camelCase
 - under_scores
 - terraform variables
 - terraform "resources"
 - module inputs
 - module outputs
 - tagging style objects vms
 - ansible group names

**Comment by merps** [comment]
As per best practices for [Terraform naming conventions](https://www.terraform-best-practices.com/naming) - camelCase or CamelCase is not suggested.  To align with defacto industry accepted conventions, along with best practices, underscores should be used.
