### ISSUE TITLE
### BIG-IP AWS Upgrade Solution

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-digital-customer-engagement-center#141]
- [x] terraform
- [x] configuration
- [x] documentation
- [x] presentation
- [x] demo

**Comment by merps** [comment]
ooo - you changed the title and it has AWS...  linky?

**Comment by jmcalalang** [comment]
Still working on it, haven’t brought anything in yet. It’s a solution to highlight upgrading bigips. It’s in aws cause I can still get 12.1.x! And same AZ will “feel” like a common deployment.

Cheers,

Jon Calalang
425.971.8991
________________________________

**Comment by merps** [comment]
aye - fun that fact and IQ 6!!! hahahaha - that said, i'll add a watch to this one because it's something we're running in our team also..

**Comment by jmcalalang** [comment]
Webinar: https://www.f5.com/de_de/company/events/webinars/tips-that-matter-and-dont-on-upgrading-big-ip

**Comment by jmcalalang** [comment]
closed, pr's complete solution is in place.

webinar: https://www.f5.com/fr_fr/company/events/webinars/tips-that-matter-and-dont-on-upgrading-big-ip
