### ISSUE TITLE
pre-commit issues

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-digital-customer-engagement-center#161]
Seems like there are a few people not using pre-commit

```
codespace ➜ ~/workspace/solutions/delivery/application_delivery_controller/big-ip/upgrade/aws (bigup-upgrade-docs) $ pre-commit run -a -vTerraform fmt............................................................Failed
- hook id: terraform_fmt
- duration: 5.63s
- files were modified by this hook

main.tf
main.tf

Terraform docs...........................................................Failed
- hook id: terraform_docs
- duration: 6.81s
- files were modified by this hook
Check for merge conflicts................................................Passed
- hook id: check-merge-conflict
- duration: 0.08s
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- duration: 0.29s
- exit code: 1
- files were modified by this hook

Fixing solutions/security/multi-cloud-connectivity-volterra/google/README.md
Fixing .github/stale.yml
Fixing solutions/security/multi-cloud-connectivity-volterra/azure/versions.tf
Fixing solutions/security/multi-cloud-connectivity-volterra/TROUBLESHOOTING.md

Sort simple YAML files...............................(no files to check)Skipped
- hook id: sort-simple-yaml
Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- duration: 0.39s
- exit code: 1
- files were modified by this hook

Fixing solutions/security/aws-inter-subnet-fw-gwlb/README.md
Fixing solutions/security/multi-cloud-connectivity-volterra/google/README.md
Fixing solutions/security/multi-cloud-connectivity-volterra/azure/README.md

Detect Private Key.......................................................Failed
- hook id: detect-private-key
- duration: 0.34s
- exit code: 1

Private key found: solutions/security/multi-cloud-connectivity-volterra/google/README.md

talisman.................................................................Passed
- hook id: talisman-commit
- duration: 0.14s
```

![pre-commit errors](https://user-images.githubusercontent.com/20847865/132767800-f3834bd7-6bcf-42da-bf06-ee8bac791f53.png)

This looks like @memes  and @JeffGiroux  for modules
@yossi-r  for gwlb @jmcalalang  for KIC and maybe @memes  for test?

I'm happy to clean them all up with a PR, but each of you needs to approve it.

**Comment by memes** [comment]
@jmcalalang  What version of `terraform-docs version` do you see? The READMEs are likely because you are on a different version.

Also, `pre-commit run -a -v` should only be used if you are not using pre-commit as a hook.

**Comment by jmcalalang** [comment]
Do we have it as a hook? I didn't think there was a trigger? That's part of the incoming changes?

Terraform docs in the dev container:

terraform-docs --version
terraform-docs version v0.9.1 7f761d3 linux/amd64 BuildDate: 2020-04-02T21:58:38+0000
codespace ➜ ~/workspace/solutions/delivery/application_delivery_controller/big-ip/upgrade/aws (bigup-upgrade-docs ✗) $

**Comment by memes** [comment]
Yeah, so at least some of the READMEs are because of differing `terraform-docs` and executing `pre-commit run -a -v`. The `run -a -v` command instructs pre-commit to run the hooks on ALL files, not just the changed files, which potentially causes a bunch of unrelated files to be updated.

`pre-commit` *should be* installed as a git hook so that it is automatically run on each git commit. I'll open an issue and update README because that instruction is missing.

The other issue is the diverging terraform-docs versions; I have mine pinned to 0.11.2, yours is 0.9.1. The proposed updated devcontainer has 0.15.

```shell
f5-digital-customer-engagement-center on  main [?] via 🐍 v3.9.4 (python-3.9.4) via 💎 v2.7.2 on ☁️  Users-711213608975 (us-west-2) on ☁️  m.emes@f5.com(us-west1)
❯ terraform-docs version
terraform-docs version 0.11.2 bd351fc darwin/amd64 BuildDate: 2021-02-22T23:52:49Z
```

**Comment by memes** [comment]
Opened related issue #162
