### ISSUE TITLE
Chrome (Mac, Windows), and all WebKit based browsers (Safari on Mac and all iOS browsers) render the documentation site with the wrong character encoding.

### ISSUE THREAD

**Issue by tmarfil** [f5devcentral/f5-digital-customer-engagement-center#172]
Install this Chrome plugin:
https://chrome.google.com/webstore/detail/set-character-encoding/bpojelgakakmcfmjfilgdlmhefphglae?hl=en

Open this example in Chrome:
https://f5-digital-customer-engagement-center.readthedocs.io/en/latest/docs/solutions/delivery/application_delivery_controller/nginx/kic/gke_labSetupGKE.html

Right-click anywhere on the screen and **Select Character Encoding** to toggle the encoding:

- **default** = Chrome incorrectly renders the site using what appears to be Western (Windows 1252) encoding. This is true for the entire site, but it's especially conspicuous on a page with apostrophes.
- **Unicode (UTF-8)** = Chrome renders the page correctly as UTF-8.

The plugin inserts a Response Header that explicitly sets the encoding:
```text/html; charset=UTF-8```

You can confirm with Chrome Developer Tools (F12).

Firefox (Mac and Windows, but not WebKit-based iOS) will render the site correctly using UTF-8.

**Comment by merps** [comment]
this appears to be the underlying readthedocs.io deployment and not so much the documentation - https://github.com/readthedocs/readthedocs.org/issues/1176
