### ISSUE TITLE
Chrome (Mac, Windows), and all WebKit based browsers (Safari on Mac and all iOS browsers) render the documentation site with the wrong character encoding.

### ISSUE THREAD

**Issue by tmarfil** [f5devcentral/f5-digital-customer-engagement-center#186]
Install this Chrome plugin:
https://chrome.google.com/webstore/detail/set-character-encoding/bpojelgakakmcfmjfilgdlmhefphglae?hl=en

Open this example in Chrome:
https://f5-digital-customer-engagement-center.readthedocs.io/en/latest/docs/solutions/delivery/application_delivery_controller/nginx/kic/gke_labSetupGKE.html

Right-click anywhere on the screen and **Select Character Encoding** to toggle the encoding:

- **default** = Chrome incorrectly renders the site using what appears to be Western (Windows 1252) encoding. This is true for the entire site, but is especially conspicuous on a page with apostrophes.
- **Unicode (UTF-8)** = Chrome renders the page correctly as UTF-8.

The plugin inserts a Response Header that explicitly sets the encoding:
```text/html; charset=UTF-8```

You can confirm with Chrome Developer Tools (F12).

Same issue previously closed by bot:
https://github.com/f5devcentral/f5-digital-customer-engagement-center/issues/172

**Comment by tmarfil** [comment]
From the developer console [F12]

```
document.characterSet
'windows-1252'
```
Test on this site: https://clouddocs.f5.com/
```
document.characterSet
'UTF-8'
```

**Comment by tmarfil** [comment]
```<meta http-equiv="content-type" content="text/html; charset=windows-1252">```

**Comment by jmcalalang** [comment]
it should already be default, but maybe we have to hardset:

https://www.sphinx-doc.org/en/master/usage/configuration.html

html_output_encoding[¶](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_output_encoding)
Encoding of HTML output files. Default is 'utf-8'. Note that this encoding name must both be a valid Python encoding name and a valid HTML charset value.
