### ISSUE TITLE
Gateway Load Balancer Terraform deployment fails due to 'Sleep' command

### ISSUE THREAD

**Issue by YannickJanssens** [f5devcentral/f5-digital-customer-engagement-center#188]
Running on a Windows 11 machine, the Sleep command doesn't exist anymore so this bit in the bigip module errors:
![image](https://user-images.githubusercontent.com/29145316/181551896-4cdeced9-d731-4722-b0af-98fe2e4999e5.png)

![image](https://user-images.githubusercontent.com/29145316/181554391-94ca9cf3-73b7-429e-9459-6c284e1cd16c.png)

Solution for me is to change the command to something Powershell-y but probably doesn't work on non-windows systems:
![image](https://user-images.githubusercontent.com/29145316/181555391-e72efb49-1ba8-4bbd-b5f7-453cfe3a90c6.png)

module location:
https://github.com/f5devcentral/f5-digital-customer-engagement-center/blob/main/solutions/security/gateway-load-balancer/azure/modules/bigip/main.tf

**Comment by JeffGiroux** [comment]
Hi, perfect timing...was looking at this code recently for other purposes and just revamped it to use the BIG-IP terraform module from the F5 PM team. Use this test branch to re-run your deployment and see if the sleep problem goes away. Technically, the module behind the scenes still calls azure vm resource and azure vm extension.

My test branch for this solution ...will PR soon - https://github.com/f5devcentral/f5-digital-customer-engagement-center/tree/gwlbUpdatesAzure/solutions/security/gateway-load-balancer/azure

The BIG-IP Azure module which is now the basis for creating the bigip in the main.tf file.
https://github.com/F5Networks/terraform-azure-bigip-module

You'll see the new bigip code block like this...
```
module "bigip" {
  count                      = var.instance_count
  source                     = "github.com/F5Networks/terraform-azure-bigip-module"
  prefix                     = var.prefix
  resource_group_name        = azurerm_resource_group.rg.name
  f5_instance_type           = var.f5_instance_type
  f5_image_name              = var.f5_image_name
  f5_product_name            = var.f5_product
  f5_version                 = var.f5_version
  f5_username                = var.f5_username
  f5_ssh_publickey           = file(var.f5_ssh_publickey)
  mgmt_subnet_ids            = [{ "subnet_id" = data.azurerm_subnet.mgmtSubnet.id, "public_ip" = true, "private_ip_primary" = "" }]
  mgmt_securitygroup_ids     = [module.nsg-mgmt.network_security_group_id]
  external_subnet_ids        = [{ "subnet_id" = data.azurerm_subnet.externalSubnet.id, "public_ip" = true, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  external_securitygroup_ids = [module.nsg-external.network_security_group_id]
  internal_subnet_ids        = [{ "subnet_id" = data.azurerm_subnet.internalSubnet.id, "public_ip" = false, "private_ip_primary" = "" }]
  internal_securitygroup_ids = [module.nsg-internal.network_security_group_id]
  availability_zone          = var.availability_zone
  custom_user_data           = local.f5_onboard1
  sleep_time                 = "30s"
  tags                       = local.tags
  #az_user_identity           = var.user_identity
}
```

**Comment by JeffGiroux** [comment]
closing, lack of response
