### ISSUE TITLE
## jumpbox aws

### ISSUE THREAD

**Issue by merps** [f5devcentral/f5-digital-customer-engagement-center#40]
- [ ] terraform
- [ ] documentation
- [ ] examples

**Comment by merps** [comment]
@vinnie357 or @yossi-r  is this the `workstation` module previously located under commitid: [a0c9e3a](https://github.com/merps/f5-digital-customer-engagement-center/commit/a0c9e3a7558d1383ccddea50e4b32090a8ba76f6).  Just wondering, apart from the incorrect pathing, why this was removed?

**Comment by vinnie357** [comment]
not 100% but I didn't see it where I expected it and jon needed it for the kic stuff.
I made one based on these: https://github.com/vinnie357/bash-onboard-templates/blob/master/terraform/aws/sca/onboard.sh

I was thinking the workspaces would
accept custom cloud init, or move to packer?

today the aws one installs:
aws cli
f5 cli
terraform
docker
coder
- f5 extension in coder
- terraform extension in coder
nginx

and:
clones a list of repos.


I was thinking about just using docker, and running customized coder instances using these:
https://github.com/vinnie357/devcontainers

and using nginx to present them, lets us use the jumpbox and all the tools without the user having to make them.

**Comment by jmcalalang** [comment]
we need to clarify the name, in code its workstation, in context we call it jumphost

other than that, it already has docker on it, its being used to present coder. it does however need awscli configured since this instance needs to talk to ecr and aws when building the nginx ingress images

**Comment by merps** [comment]
cheers @vinnie357 & @jmcalalang - left of center suggestion if you would humor me - along the lines of what you are thinking and I am sure @JeffGiroux or FouadC can shoot me down on Azure or @memes on GCP, along the line of the initial commit and to be consistent can we either use jumphost/jumpbox (accepted norm) and then dependent on CSP install the relavent tools?  (aws-cli, gcp, azure)

**Comment by vinnie357** [comment]
@merps oh.
yeah jumphost/jumpbox/bastion/bastionhost/workspace
I my only ask is whatever we pick is the same for all "providers/clouds" 
I am voting for jumphost since we are using it with public addresses to make the labs easier to run.
I feel like bastion has a different expectation only accessible in the cloud env/shell?
