### ISSUE TITLE
UDF Jumphost Documentation

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-digital-customer-engagement-center#42]
UDF jumphost is in the UDF environment blueprint: F5 Digital Customer Engagement Center

This blueprint is used in lieu of a customer installing VSCode and terraform, most common in F5 lead training events. Documentation is needed getting for a user to a known working state before the consumer is ready to jump into working on solutions/modules.

**Comment by merps** [comment]
@jmcalalang - is this with egress access from UDF to CSP,  Is that the intention of this?

**Comment by jmcalalang** [comment]
Yeah, I'm lab situations we might not have dependencies installed on the consumers computers (tf,docker,Ansible etc). This jumphost acts as a launching instance, after code is launched students will access the workstation like all other users.

Jumphost is already created in UDF this is docs. Can share blueprint if needed

**Comment by jmcalalang** [comment]
Also this is how consumers can get CSP creds

**Comment by jmcalalang** [comment]
UDF jumphost is complete: https://f5-digital-customer-engagement-center.readthedocs.io/en/latest/docs/usage/f5_udf_getting_started.html
