### ISSUE TITLE
GCP initial infra module

### ISSUE THREAD

**Issue by memes** [f5devcentral/f5-digital-customer-engagement-center#43]
GCP infra module will take care of provisioning a network, secrets manager, GCR, API enablement, etc for solutions on Google Cloud.

## Steps
1. [x] Refactor [network/min](modules/google/terraform/network/min) to be standard of three regional networks (VPCs)
2. [x] Infra module which *augments* _network/min_ functionality
3. [ ] Refactor references to _network/min_ and _network/max_ to use `infra` module
4. [x] Delete ~_network/min_ and~ _network/max_ modules
5. [x] Update CODEOWNERS to reflect new module

**Comment by jmcalalang** [comment]
I like this, it's a baseline for everything

**Comment by memes** [comment]
Marking as closed now that PR #122 has been merged
