### ISSUE TITLE
AWS Consolidated Network Module

### ISSUE THREAD

**Issue by merps** [f5devcentral/f5-digital-customer-engagement-center#44]
To simplify the re-use of module inter-dependencies this enhancement proposes:
* introduce network min as feature flag for module call
* network max, CIS & SCA in later iterations.

the proposed format of this would look like:
```hcl
variable "network_deployment" {
   type = map(bool)
   default = {
       min_network_enabled = true
       max_network_enabled = false
   ...
   }
}
```
This would allow the passing of the variable to subsequent child modules, as such;
```hcl
module “aws_network” {
  source = “https://github.com/f5devcentral/f5-digital-customer-engagement-center/modules/aws/terraform/network”
  module_features = var.network_deployment
  ...
}

**Comment by memes** [comment]
I'd propose that the base `network` module creates a min network in the absence of any features; if that is consistent with other's thinking, I suggest that the `min_network_flag` is redundant since that outcome occurs when other flags are not present.

E.g. if min network is the baseline, then this is same as example above, but omitting the inferred baseline requirement.

```hcl
variable "network_deployment" {
  type = map(bool)
  default = {
    max_network_enabled = false
    ...
   }
}
```

With that, do we prefer a max flag that turns on almost all the bells and whistles as appropriate for the platform, or flags for individual features? Of course, both could be valid too but I'd like us to propose one standard we use as much as possible. So is *max* the feature, or *cis_approved* (or whatever the appropriate naming for feature?


E.g. per-feature flag on GCP could be:

```hcl
variable "network_deployment" {
  type = map(bool)
  default = {
    isolated_internal_vpcs = false
    private_dns = false
    ...
   }
}
```

Thoughts?

**Comment by memes** [comment]
Natch, we'd need to *define* what each of those flags do :)

**Comment by merps** [comment]
@memes the initial module would be the `min` network as defined thus far... i'd suggest the additional flags for customisation of `max` construct?  how's that float?

**Comment by memes** [comment]
Sure, my comment is not about what makes min/max, but how we define and add features later.

**Comment by vinnie357** [comment]
goal for the min/max was to be as simple as possible for the consumers.

min/max/custom?  where custom is max with options?

**Comment by merps** [comment]
of course... completely agree there man.. mvp out the door and all that... :-) we can create sub-tasks/issues to support the additional features for each CSP?

**Comment by merps** [comment]
ooo - custom... nice call @vinnie357 - so the next question is the deployment for `max` that is different to `custom`?

**Comment by memes** [comment]
Network is the abstraction layer; we're now taking this conversation back to implementation. How min/max/custom is implemented is distinct from what we mean by min/max/custom. The idea of flags was to be able to postpone a concrete definition, but have a sane baseline (min).

So if there's min, max, and custom should only custom accept flags, and if so we're back to what defines min and max on each csp.

**Comment by merps** [comment]
the hiccup with default of `min` @memes would be the reconfiguration - speaking to AWS VPC creation - of some components so following that thought I would suggest using:
```hcl
variable "network_deployment" {
  type = map(bool)
  default = {
    min_network_enabled = false
    ...
   }
}
``` 
would that work with GCP?

**Comment by memes** [comment]
@merps - not a problem for GCP. Any redefinition of the module params could cause a rebuild but hey that's why we have automation.

I'm trying to avoid cognitive overload or additional validation

```hcl
variable "network_deployment" {
  type = map(bool)
  default = {
    min_network_enabled = true
    max_network_enabled = true
    ...
   }
}
```

**Comment by memes** [comment]
And we can punt this to the maintainers

**Comment by merps** [comment]
initial commit with working k8s tagging, etc. for `create_min` flag - [`1e53506`](https://github.com/merps/f5-digital-customer-engagement-center/commit/1e5350672af7fc7aa4aa06b4ae5d35084881bdce)
