### ISSUE TITLE
AWS Network Modules need tags to be passed

### ISSUE THREAD

**Issue by jmcalalang** [f5devcentral/f5-digital-customer-engagement-center#51]
KIC solution requires that special tags are located on the public subnets for ELB's to be created. 

Doesn't come from the community module:
https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1005

If I add these to the subnets after TF, they will be erased on a re-run.

awscli command examples:

aws ec2 create-tags \
    --resources subnet-0121c5ac21a90c019 subnet-0e3057b6d65a3166d \
    --tags Key=kubernetes.io/cluster/my-cluster-3820603181,Value=shared   Key=kubernetes.io/role/elb,Value=1

**Comment by merps** [comment]
@jmcalalang - I have made some changes to the aws network module for min - it is named [`terraform-aws-vpc-dcec`](https://gitlab.wirelessravens.org/f5labs/terraform-aws-vpc-dcec) - I am yet to create a PR because, well, haven't sorted the tagging for `aws_max` yet.

**Comment by merps** [comment]
linked to Issue https://github.com/f5devcentral/f5-digital-customer-engagement-center/issues/44
