### ISSUE TITLE
proposed base solution examples library

### ISSUE THREAD

**Issue by vinnie357** [f5devcentral/f5-digital-customer-engagement-center#80]
Rather than polluting the solutions folder with examples that don't solve something, we want to provide a library of sample code such as a single big-ip or nginx+ instance in each provider. This should help new solution creators get started.

codespace ➜ ~/workspace/library (main) $ tree
.
├── big-ip
│   └── azure
├── nginx+
│   └── azure
├── nginx-controller
│   └── azure
└── volterra
    └── voltmesh

8 directories, 0 files

example:
- provider
- network
- big-ip

**Comment by jmcalalang** [comment]
I still really like the library, since its concept is similar to code. I'm checking out that product and going to use it in my new solution.

**Comment by merps** [comment]
silly question - rather than product should we carve by cloud?
